//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace ClinicAppointments.SQL
{

  public partial class Appointments
  {
    public int PatientId { get; set; }
    public int SpecialtyId { get; set; }
    public System.DateTime AppointmentDateTime { get; set; }
    public int Id { get; set; }

    [ForeignKey("PatientId")]
    public virtual Patients Patients { get; set; }

    [ForeignKey("SpecialtyId")]
    public virtual Specialties Specialties { get; set; }
  }
}
