//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAppointments.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int PatientId { get; set; }
        public int SpecialtyId { get; set; }
        public System.DateTime AppointmentDateTime { get; set; }
        public int Id { get; set; }
    
        public virtual Patients Patients { get; set; }
        public virtual Specialties Specialties { get; set; }
    }
}
