//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAppointments.SQL
{
  using System.Data.Entity;

  public partial class ClinicDB : DbContext
  {
    public ClinicDB() : base("name=ClinicDB")
    {
    }

    static ClinicDB()
    {
      Database.SetInitializer<ClinicDB>(new ClinicDBInit());
    }

    public static ClinicDB Create()
    {
      return new ClinicDB();
    }

    public class ClinicDBInit : NullDatabaseInitializer<ClinicDB> { }

    public virtual DbSet<Appointments> Appointments { get; set; }
    public virtual DbSet<Patients> Patients { get; set; }
    public virtual DbSet<Specialties> Specialties { get; set; }
  }
}
